### ISSUE TITLE
Include study resources as you go along?

### ISSUE THREAD

**Issue by chinmaydd** [cskksc/tt101#1]
It would be really helpful for someone interested in the topic to have some resources(not just for Agda, but Type Theory in general) to start off with. This could also help understand the problems and code being written.

**Comment by cskksc** [comment]
@chinmaydd Most of the theorems are from this [book](https://svn.divms.uiowa.edu/repos/clc/projects/agda/book/book.pdf).  Check [out](https://vimeo.com/117221082) [these](https://vimeo.com/61576198) [videos](https://www.youtube.com/watch?v=-CbFj9K9AQg) to see Idris in action. Most of these languages are based on Martin Löf's type [theory](http://www.cse.chalmers.se/research/group/logic/book/book.pdf). I haven't read this yet, but it's on my TODO list.

**Comment by cskksc** [comment]
@chinmaydd Oh, and also, Dan Friedman and David Christiansen are working on another "Little" book on dependently typed programming in Scheme. Keep an out for that. It'll be great!

**Comment by chinmaydd** [comment]
That's awesome. Thanks a lot! :smile:

**Comment by cskksc** [comment]
@chinmaydd No, thank you! You brought up a very important point. I'll remember to include links to the resources as I implement more stuff :-)
